remote_theme: pmarsceill/just-the-docs
title: CS-1400 with Ruiz
description: Python3 references
<<<<<<< HEAD
url: "https://cs-1030.github.io"
=======
url: "https://cs-1400.github.io" 
>>>>>>> main
permalink: /:title/


# Upper nav links
aux_links:
  "Python Docs": "https://docs.python.org/3/"
aux_links_new_tab: true

# pages included in page navigation and search
include:
  - _pages
exclude:
  - README.md

# Footer on every page
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 Bianca Ruiz. Distributed by an <a href=\"https://github.com/CS-1030/CS-1030.github.io/tree/master/LICENSE.txt\">MIT license.</a>"
